services:
  kafka:
    image: confluentinc/confluent-local:7.6.0
    container_name: kafka-oaevents
    ports:
      - "9092:9092"
    environment:
      # Para que se creen los topics automaticamente
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      # Definimos los roles de seguridad
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      # Abrimos los puertos (29092 red de Docker, 9092 para fuera/K8s, 29093 para el controlador)
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093,PLAINTEXT_HOST://0.0.0.0:9092
      # Publicamos "host.docker.internal" en el puerto 9092 para que SpringBoot se conecte
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-oaevents:29092,PLAINTEXT_HOST://host.docker.internal:9092

